name: Deploy Chatbot Website

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Step 3: Inject your API key into chat.js
      - name: Add API key to chat.js
        run: |
          sed -i "s|YOUR_API_KEY|${{ secrets.API_KEY }}|g" chat.js

      # Step 4: Deploy all files to S3
      - name: Deploy static files to S3
        run: aws s3 sync . s3://your-chatbot-bucket-name --delete
